@startuml
' 패키지 별로 구분
package ControllerNetwork {
    class Controller {
        +__init__()
        +forward()
        +post_process()
    }
}

package QuantumNetwork {
    class QuantumLayer {
        +__init__()
        +forward()
    }

    class QNet {
        +__init__()
        +forward()
    }

    QNet --> QuantumLayer : uses
}

package datasets {
    class CustomDataset {
        +__init__()
        +__len__()
        +__getitem__()
    }

    class DataLoaderUtils {
        +splittingIRIS()
        +IRISDataLoaders()
    }

    DataLoaderUtils --> CustomDataset : returns
}

package schemes {
    class SchemeFunctions {
        +train()
        +test()
        +controller_train()
        +scheme()
    }
}

main -> Controller : instantiates
main -> QNet : instantiates
main -> IRISDataLoaders : calls
main -> scheme : calls

@enduml
